// Generated by CoffeeScript 1.6.3
var app, config, express, fs, maxAge, path, routes, staticDir;

path = require('path');

express = require('express');

config = require('./config').config;

routes = require('./routes');

fs = require('fs');

app = express();

app.configure(function() {
  var viewsRoot;
  viewsRoot = path.join(__dirname, 'views');
  app.set('view engine', 'jade');
  app.set('views', viewsRoot);
  app.use(express.cookieParser());
  app.use(express.session({
    secret: config.session_secret
  }));
  app.use(express.urlencoded());
  return app.use(express.json());
});

maxAge = 3600000 * 24 * 30;

staticDir = path.join(__dirname, 'public');

app.configure('development', function() {
  app.use(express["static"](staticDir));
  return app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

app.configure('production', function() {
  app.use(express["static"](staticDir, {
    maxAge: maxAge
  }));
  return app.set('view cache', true);
});

routes(app);

app.listen(config.port, config.ip);

console.log("Giccoo WeChat start.");
