// Generated by CoffeeScript 1.6.3
exports.config = {
  debug: true,
  name: 'Giccoo-WeChat',
  description: 'WeChat',
  version: '0.1.0',
  session_secret: 'giccoo_wechat',
  auth_cookie_name: 'giccoo_wechat',
  ip: '127.0.0.1',
  port: 8081,
  list_count: 20,
  wechat_token: "kelvinbuild",
  plugins: []
};
