// Generated by CoffeeScript 1.6.3
var post, wechat;

wechat = require('./controllers/wechat');

post = require('./controllers/wechat-post');

module.exports = function(app) {
  app.get('/', wechat.index);
  app.post('/', wechat.index);
  app.get('/gettoken', post.gettoken);
  return app.get('/getmenu', post.getmenu);
};

console.log("routes loaded.");
