// Generated by CoffeeScript 1.6.3
var wechat;

wechat = require('./controllers/wechat');

module.exports = function(app) {
  app.get('/', wechat.index);
  return app.post('/', wechat.index);
};

console.log("routes loaded.");
