// Generated by CoffeeScript 1.7.1
var lottery, post, wechat;

wechat = require('./controllers/wechat');

post = require('./controllers/wechat-post');

lottery = require('./controllers/lottery');

module.exports = function(app) {
  app.get('/', wechat.index);
  app.post('/', wechat.index);
  app.get('/lottery', lottery.index);
  app.get('/lottery-work', lottery.work);
  app.get('/gettoken', post.gettoken);
  app.get('/getmenu', post.getmenu);
  return app.get('/word', wechat.word);
};

console.log("routes loaded.");
