// Generated by CoffeeScript 1.7.1
var EventProxy, Lottery, Lottery_x_list, Segment, Ut, config, fs, xml2js;

Lottery = require('../proxy').Lottery;

Lottery_x_list = require('../proxy').Lottery_x_list;

fs = require('fs');

xml2js = require('xml2js');

EventProxy = require('eventproxy');

config = require('../config').config;

Segment = require('segment').Segment;

Ut = require('../lib/util');

exports.lot = function(req, res, next) {
  var lot;
  lot = req.params.lot;
  if (lot === 'onetwo') {
    return res.render('lottery-onetwo');
  }
};

exports.work = function(req, res, next) {
  console.log(req.query);
  return res.render('lottery-work');
};
