// Generated by CoffeeScript 1.7.1
var APPID, EventProxy, REDIRECT_URI, STATE, Segment, config, fs, scope, xml2js;

fs = require('fs');

xml2js = require('xml2js');

EventProxy = require('eventproxy');

config = require('../config').config;

Segment = require('segment').Segment;

APPID = "wx86b8da13792d7a54";

REDIRECT_URI = "http://wechat.giccoo.com/lottery-work";

STATE = "ok";

scope = "snsapi_userinfo";

exports.index = function(req, res, next) {
  var code;
  code = req.body.code;
  if (code != null) {
    return res.render('lottery');
  } else {
    return res.redirect('https://open.weixin.qq.com/connect/oauth2/authorize?appid=' + APPID + '&redirect_uri=' + REDIRECT_URI + '&response_type=code&scope=' + scope + '&state=' + STATE + '#wechat_redirect');
  }
};

exports.work = function(req, res, next) {
  console.log(req);
  return res.render('lottery');
};
