// Generated by CoffeeScript 1.6.3
var access_token, checkMenus, checkToken, getToken, https, options_create_menu, options_get_access_token, options_get_menu, post_data, querystring, sendMenus, url;

https = require('https');

url = require('url');

querystring = require('querystring');

access_token = {};

options_create_menu = {
  host: "https://api.weixin.qq.com/cgi-bin/menu/create?access_token=",
  method: 'POST'
};

options_get_menu = {
  host: "https://api.weixin.qq.com/cgi-bin/menu/get?access_token=",
  method: 'GET'
};

options_get_access_token = {
  host: "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wx86b8da13792d7a54&secret=f93ec247a40c59eccbf4bc8b5ac5721c",
  method: 'GET'
};

post_data = {
  button: [
    {
      type: "click",
      name: "今日歌曲",
      key: "MUSIC"
    }, {
      type: "click",
      name: "歌手简介",
      key: "SINGER"
    }
  ]
};

checkToken = function(callback) {
  if (access_token.date && access_token.date > new Date().getTime()) {
    callback(false);
    return true;
  } else {
    getToken(callback);
    return false;
  }
};

getToken = function(callback) {
  var request;
  request = https.get(options_get_access_token.host, function(result) {
    console.log('STATUS: ' + result.statusCode);
    console.log('HEADERS: ' + JSON.stringify(result.headers));
    result.setEncoding('utf8');
    return result.on('data', function(chunk) {
      var obj;
      console.log('BODY: ' + chunk);
      obj = JSON.parse(chunk);
      if (obj.access_token) {
        access_token = obj;
        access_token.date = new Date().getTime() + obj.expires_in * 1000;
        return callback(false);
      } else {
        return callback('There is no token');
      }
    });
  });
  request.write('\n');
  return request.end();
};

sendMenus = function() {
  var op, p, request, u;
  u = url.parse(options_create_menu.host);
  p = u['port'] ? u['port'] : 80;
  op = {
    hostname: u['host'],
    port: 443,
    path: u['path'] + access_token.access_token,
    method: 'POST'
  };
  console.log(op, p);
  request = https.request(op, function(res) {
    console.log("statusCode: ", res.statusCode);
    console.log("headers: ", res.headers);
    return res.on('data', function(chunk) {
      var obj;
      obj = JSON.parse(chunk);
      return console.log(obj);
    });
  });
  request.write(JSON.stringify(post_data) + '\n');
  return request.end();
};

checkMenus = function() {
  var request;
  request = https.get(options_get_menu.host + access_token.access_token, function(res) {
    console.log("statusCode: ", res.statusCode);
    console.log("headers: ", res.headers);
    return res.on('data', function(chunk) {
      var obj;
      obj = JSON.parse(chunk);
      return console.log(obj);
    });
  });
  request.write('\n');
  return request.end();
};

exports.gettoken = function(req, res, next) {
  checkMenus();
  return res.render('wechat-ctrl');
};

exports.getmenu = function(req, res, text) {
  console.log(new Date().getTime(), access_token.date);
  return checkToken(function(err) {
    if (err) {
      return false;
    }
    sendMenus();
    return res.render('wechat-ctrl');
  });
};
