// Generated by CoffeeScript 1.6.3
var EventProxy, checkSignature, config, crypto, xml2js;

crypto = require('crypto');

xml2js = require('xml2js');

EventProxy = require('eventproxy');

config = require('../config').config;

checkSignature = function(query, token) {
  var arr, nonce, shasum, signature, timestamp;
  signature = query.signature;
  timestamp = query.timestamp;
  nonce = query.nonce;
  shasum = crypto.createHash('sha1');
  arr = [token, timestamp, nonce].sort();
  shasum.update(arr.join(''));
  return shasum.digest('hex') === signature;
};

exports.index = function(req, res, next) {
  console.log(req.parse);
  return res.send(checkSignature(req.parse, config.wechat_token));
};
