// Generated by CoffeeScript 1.7.1
var Admin, models;

models = require('../models');

Admin = models.Admin;

exports.getUserLogin = function(name, passwd, callback) {
  return Admin.findOne({
    username: name,
    password: passwd
  }, null, {
    sort: {
      create_at: 1
    }
  }, callback);
};

exports.saveNew = function(name, passwd, callback) {
  var administrator;
  administrator = new Admin();
  administrator.username = name;
  administrator.password = passwd;
  return administrator.save(callback);
};
