// Generated by CoffeeScript 1.7.1
var Lottery, models;

models = require('../models');

Lottery = models.Lottery;

exports.getLotter = function(code, callback) {
  return Lottery.findOne({
    randomcode: code
  }, null, {
    sort: {
      create_at: 1
    }
  }, callback);
};

exports.getLotterByLot = function(lot, callback) {
  return Lottery.find({
    lottery: lot
  }, null, {
    sort: {
      create_at: 1
    }
  }, callback);
};

exports.create = function(randomCode, callback) {
  var lot;
  lot = new Lottery();
  lot.randomcode = randomCode;
  return lot.save(callback);
};
