// Generated by CoffeeScript 1.7.1
var Message, models;

models = require('../models');

Message = models.Message;

exports.getmsg = function(callback) {
  return Message.find({}, null, {
    sort: {
      create_at: 1
    }
  }, callback);
};

exports.saveText = function(openid, type, text, msgid, callback) {
  text = new Message();
  text.openid = openid;
  text.type = type;
  text.text = text;
  text.msgid = msgid;
  return text.save(callback);
};

exports.saveImg = function(openid, type, picurl, msgid, mediaid, callback) {
  var img;
  img = new Message();
  img.openid = openid;
  img.type = type;
  img.picurl = picurl;
  img.msgid = msgid;
  img.mediaid = mediaid;
  return img.save(callback);
};
