// Generated by CoffeeScript 1.7.1
var OneTwo, models;

models = require('../models');

OneTwo = models.OneTwo;

exports.getOneTwos = function(callback) {
  return OneTwo.find({}, callback);
};

exports.getLottery = function(openid, backup, callback) {
  console.log("openid:", openid, backup);
  return OneTwo.findOne({
    openid: openid
  }, callback);
};

exports.newAndSave = function(openid, lot, callback) {
  var one;
  one = new OneTwo();
  one.openid = openid;
  one.lot = lot;
  return one.save(callback);
};
