// Generated by CoffeeScript 1.7.1
var User, models;

models = require('../models');

User = models.User;

exports.getUserAdmins = function(callback) {
  return User.find({
    is_admin: true
  }, null, {
    sort: {
      create_at: 1
    }
  }, callback);
};

exports.getUsers = function(callback) {
  return User.find({}, null, {
    sort: {
      create_at: -1
    }
  }, callback);
};

exports.getUserLogin = function(name, pass, callback) {
  return User.find({
    name: name,
    pass: pass
  }, callback);
};

exports.getUserByNames = function(names, callback) {
  if (names.length === 0) {
    return callback(null, []);
  }
  return User.find({
    name: {
      $in: names
    }
  }, callback);
};

exports.getUserById = function(id, callback) {
  return User.findOne({
    _id: id
  }, callback);
};

exports.getUsersByQuery = function(query, opt, callback) {
  return User.find(query, null, opt, callback);
};

exports.newAndSave = function(name, pass, email, avatar_url, active, sex, title, callback) {
  var user;
  user = new User();
  user.name = name;
  user.pass = pass;
  user.email = email;
  user.avatar = avatar_url;
  user.sex = sex;
  user.title = title;
  user.active = false;
  return user.save(callback);
};
