// Generated by CoffeeScript 1.7.1
var BackSendSchema, ObjectId, Schema, config, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

config = require('../config');

ObjectId = Schema.ObjectId;

BackSendSchema = new Schema({
  openid: {
    type: ObjectId
  },
  create_at: {
    type: Date,
    "default": new Date()
  }
});

mongoose.model('BackSend', BackSendSchema);
