// Generated by CoffeeScript 1.7.1
var LotterySchema, Schema, config, mongoose;

mongoose = require('mongoose');

Schema = mongoose.Schema;

config = require('../config');

LotterySchema = new Schema({
  randomcode: {
    type: String,
    index: true
  },
  lottery: {
    type: String
  },
  num: {
    type: Number
  },
  create_at: {
    type: Date,
    "default": Date.now
  }
});

mongoose.model('Lottery', LotterySchema);
